services:

  postgres:
    image: postgres:14.20-bookworm
    container_name: pg-bot
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg-bot-data:/var/lib/postgresql/data
    networks:
      - dbnet

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - dbnet

  tgbot:
    build: .
    image: tgbot:1.5.5
    container_name: bot
    ports:
      - "8000:8000"
    logging:
      driver: "journald"
      options:
        tag: "{{.Name}}"
    restart: unless-stopped
    volumes:
      - ./:/r4bot
    env_file:
      - .env
    networks:
      - dbnet
    depends_on:
      - postgres

networks:
  dbnet:
    driver: bridge

volumes:
  pg-bot-data:
