"""Change Order.user_id FK to User.user_id

Revision ID: e507602a0b37
Revises: 3d997cd74a67
Create Date: 2026-01-25 11:10:25.125693

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e507602a0b37"
down_revision: Union[str, Sequence[str], None] = "3d997cd74a67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("orders_user_id_fkey", "orders", type_="foreignkey")
    op.alter_column(
        "orders",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.execute(
        "UPDATE orders SET user_id = users.user_id FROM users WHERE orders.user_id = users.id"
    )
    op.create_foreign_key(None, "orders", "users", ["user_id"], ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.execute(
        "UPDATE orders SET user_id = users.id FROM users WHERE orders.user_id = users.user_id"
    )
    op.alter_column(
        "orders",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.create_foreign_key(
        op.f("orders_user_id_fkey"), "orders", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
