"""OrderItemTable extension

Revision ID: ab5c9e152731
Revises: e507602a0b37
Create Date: 2026-04-25 11:24:09.083133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab5c9e152731'
down_revision: Union[str, Sequence[str], None] = 'e507602a0b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item_association', sa.Column('item_name', sa.String(length=512), nullable=True))
    op.alter_column('order_item_association', 'item_hash_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_item_association', 'item_hash_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('order_item_association', 'item_name')
    # ### end Alembic commands ###
