"""add unit price to order_item

Revision ID: 3d997cd74a67
Revises: 434ab513ad16
Create Date: 2026-01-25 10:53:31.342782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d997cd74a67'
down_revision: Union[str, Sequence[str], None] = '434ab513ad16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item_association', sa.Column('unit_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item_association', 'unit_price')
    # ### end Alembic commands ###
